---
deployment:
      tasks:
        - export DEPLOYPATH=/home/<username>/public_html/<app_folder>
        - /bin/cp <file_name> $DEPLOYPATH 
        - /bin/cp /<sub_folder>/<file_name> $DEPLOYPATH 
        - /bin cp * $DEPLOYPATH 
        - /bin cp /<sub_folder>/* $DEPLOYPATH 